Weather icons
luminator-technology-group/WeatherApp pull request #1
Opened 2024-02-12 13:45 UTC by KlaudiaLum

2024-02-12 14:07 UTC, GustavBlomqvist requested changes

2024-02-12 14:07 UTC, GustavBlomqvist commented on src/app/weather-icon/weather-icon.component.ts
> +
Remove this

2024-02-12 14:07 UTC, GustavBlomqvist commented on src/app/weather-icon/weather-icon.component.ts
>    weatherData: any;
Icon Value should be an `@Input`

2024-02-12 14:07 UTC, GustavBlomqvist commented on src/app/weather-icon/weather-icon.component.ts
No Need to call service in this component

2024-02-13 10:40 UTC, KlaudiaLum commented on src/app/weather-icon/weather-icon.component.ts
> +
Done

2024-02-13 10:40 UTC, KlaudiaLum commented on src/app/weather-icon/weather-icon.component.ts
>    weatherData: any;
Done

2024-02-13 10:41 UTC, KlaudiaLum commented on src/app/weather-icon/weather-icon.component.ts
Done , but now when I change value in postman the API dosen't update.

2024-02-13 15:25 UTC, GustavBlomqvist approved these changes
Looks really good. Nice cleanup. 

The value for the weather icon is only read on startup so that's why it's not updating.
This is fine for now. I've added a few comment, only just cleanups. LGTM

2024-02-13 15:25 UTC, GustavBlomqvist commented on src/app/app.component.html
We should delete this empty file

2024-02-13 15:25 UTC, GustavBlomqvist commented on src/app/weather-icon/weather-icon.component.html
This empty file should be deleted

2024-02-13 15:25 UTC, GustavBlomqvist commented on src/app/weather-icon/weather-icon.component.ts
> + constructor() { }
We don't need this empty constructor

2024-02-14 10:25 UTC, GustavBlomqvist approved these changes

2024-02-14 14:35 UTC, merged